"""empty message

Revision ID: efae95867efe
Revises: 06cbe628e446
Create Date: 2021-03-10 15:54:06.165607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efae95867efe'
down_revision = '06cbe628e446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'follower', ['id'])
    op.create_unique_constraint(None, 'message', ['user_from_id'])
    op.create_unique_constraint(None, 'message', ['user_to_id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user_game', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_game', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_constraint(None, 'follower', type_='unique')
    # ### end Alembic commands ###
